---
# - name: Incedent Response Info

- hosts: windows
  
  tasks:


- hosts: ubuntu

  tasks:
  
    - name: Logged in Users
      shell:  echo "SELECT * from logged_in_users" | osqueryi
      #List the currently logged in users on the box
  
    - name: Recent Login's
      shell: echo "SELECT * from LAST limit 100" | osqueryi 
    
    - name: Process Information
      shell: echo "SELECT pid,name,uid,parent,path,on_disk,total_size,user_time,system_time FROM processes" | osqueryi 
    
    - name: Suspicious Connections
      shell: echo "SELECT remote_address,protocol,remote_port from process_open_sockets where remote_port not in (0,80,443)" | osqueryi
