---
# - name: Incedent Response Info

- hosts: windows
	
  tasks:


- hosts: ubuntu

  tasks:
  	
    - name: Logged in Users
      shell: osqueryi "SELECT * from logged_in_users"
      #List the currently logged in users on the box
  
    - name: Recent Login's
      shell: osqueryi "SELECT * from LAST limit 100"
      #List the last 100 user logins on the system
      #What limit should be used?? Could this be filtered by time/date??
    
    - name: Process Information
      shell: osqueryi "SELECT pid,name,uid,parent,path,on_disk,total_size,user_time,system_time FROM processes"
      #Working osquery command to select PID|NAME||UID|PPID|PATH|Bin on Disk|MemUsage|UserTime|Kernel_Time
    
    - name: Suspicious Connections
      shell: ss -tup | grep -v :80 | grep -v :443
